### ISSUE TITLE
Create Fibonacci demo app

### ISSUE THREAD

**Issue by beeme1mr** [johannes-b/kubecon22#2]
Requirements:

- [x] Fork OpenFeature repo
- [x] Publish to container register
- [x] Create external fib service
- [x] Write k6 tests
- [x] Support Jaeger Exporter
- [ ] Document requirements

Artifacts:
- Forked repo: https://github.com/beeme1mr/kubecon-demo
- Get latest docker image: `docker pull ghcr.io/beeme1mr/kubecon-demo:latest`
- Get latest Fib3r image: `docker pull ghcr.io/beeme1mr/fib3r-kubecon-demo:latest`

**Comment by beeme1mr** [comment]
Run the main app:
`docker run -p 30000:30000 -it ghcr.io/beeme1mr/kubecon-demo:latest`

Run the Fib3r service:
`docker run -p 30001:30001 -it ghcr.io/beeme1mr/ghcr.io/beeme1mr/fib3r-kubecon-demo:latest`

**Comment by beeme1mr** [comment]
To run k6 tests:

1. Install k6 CLI
2. run `git clone https://github.com/beeme1mr/kubecon-demo.git`
3. cd k6
4. run `k6 run -e BASE_URL=http://localhost:30000 --duration 10s --vus 1 calculate.js`

**Comment by beeme1mr** [comment]
I've updated the flag configuration to support the new fib service. It's disabled by default.

**Comment by johannes-b** [comment]
@beeme1mr thanks for providing the K6 test. I will now try to execute them using the job-executor-service as described here: https://github.com/keptn-contrib/artifacthub/tree/main/k6/1.0.0

Once I have a running test, I will let you know.

**Comment by beeme1mr** [comment]
{
  "if": [
   { "in": ["k6", { "var": "userAgent" }] },
   "on",
   null
  ]
}

**Comment by johannes-b** [comment]
With the latest commits, I uploaded the artifacts required for deploying **fib3r**.
E.g, see: https://github.com/johannes-b/kubecon22/commit/ca729fc6ee6fa6761ca3277cadad36589ed224ca 

I could also successfully check that changing the password (https://github.com/my-keptn-tests/fibonacci/blob/production/fibonacci/helm/fibonacci/templates/deployment.yaml#L34) causes the main app to fail. 

Open item:
- [ ] A failing k6s test should return a `test.finished` with `result=failed` in order to react to it.
